config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :accounts

  get 'search/' => 'search#index', as: :search
  get 'search/:q' => 'search#index'

  resources :import do
    post 'import_csv', on: :collection
  end

  root 'transactions#index'

end

app/views/layouts/_navigation.haml
%header.navbar.navbar-inverse
  %nav.navbar-inner
    .container

      = link_to 'Bernard', root_path, class:'brand'

      .nav-collapse.collapse
        %ul.nav
          %li= link_to 'All transactions', transactions_path
          = render '/accounts/menu'
          %li=link_to 'Budgets', budgets_path
          %li= link_to 'Import', import_index_path


        = form_tag(search_path, method: :get, class: 'navbar-search pull-right') do
          = text_field_tag 'q', params[:q], placeholder: 'Search', class: 'search-query'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Bernard"
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield(:head)
  %body
    = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer