config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :accounts

  get 'search/' => 'search#index', as: :search
  get 'search/:q' => 'search#index'

  resources :import do
    post 'import_csv', on: :collection
  end

  root 'transactions#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  # pm_type
  # 0 Checking
  # 1 Cash
  # 2 Credit Card
  # 3 Asset
  # 4 Liability
  # 5 Online
  # 6 Savings
  # 7 Money Market
  # 8 Credit Line
  #

  scope :active, ->     { where(deleted:false) }

  has_many :transactions
  has_many :splits, foreign_key: "transfer_to_account_id"

  PM_TYPES = ['Checking', 'Cash','Credit Card','Asset','Liability','Online','Savings','Money Market','Credit Line']

  def type_name
    PM_TYPES[pm_account_type]
  end


  def active_transactions
    transactions.transaction_includes.active.balance
  end

  def basic_balance
    transactions.active
  end

  def cleared_balance
    basic_balance.cleared.sum(:amount)
  end

  def current_balance
    basic_balance.before_today.sum(:amount)
  end

  def future_balance
    basic_balance.sum(:amount)
  end

  def available_credits
    0
  end

  def available_funds
    basic_balance.sum(:amount)
  end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.active
  end

  def show
    @account = Account.find(params[:id])
    @transactions = @account.active_transactions
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.haml
%tr
  %td= link_to account.name, account
  %td.currency= money account.cleared_balance
  %td.currency= money account.current_balance
  %td.currency= money account.current_balance
  %td.currency= money account.current_balance
  %td.currency= money account.current_balance

app/views/accounts/_menu.haml
%li.dropdown
  = link_to '#', :class => 'dropdown-toggle', 'data-toggle' => 'dropdown' do
    Account
    %b.caret
  %ul.dropdown-menu(role="menu" aria-labelledby="dLabel")
    %li= link_to "All accounts", accounts_path
    %li.divider
    - @menu_accounts.active.each do |account|
      %li
        = link_to account_path(account) do
          =account.name
          .label.label-inverse.pull-right
            = money account.current_balance

app/views/accounts/index.haml
%h1 Accounts

%table.table-bordered
  %thead
    %tr
      %th Name
      %th Cleared balance
      %th Current balance
      %th Future balance
      %th Available credits
      %th Available funds

  %tbody
    - @accounts.each do |account|
      = render account

app/views/accounts/show.haml
%h1
  = @account.name
  = money @account.current_balance

%h2 
  Transactions
  = ['(',@account.transactions.count, ')'].join


= render_transactions @transactions.group_by {|t| t.date.to_s(:short_date) } , show_balance: true